"""initial schema

Revision ID: b09c49de54d9
Revises: 
Create Date: 2026-08-29 14:33:38.897631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b09c49de54d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('whatsapp_number', sa.Text(), nullable=False),
    sa.Column('capability', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_number', 'capability', 'status', name='uq_conversation_states_active_per_capability')
    )
    op.create_index(op.f('ix_conversation_states_whatsapp_number'), 'conversation_states', ['whatsapp_number'], unique=False)
    op.create_table('gateway_activity_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('incoming_message', sa.Text(), nullable=True),
    sa.Column('resolved_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_activity_log_correlation_id'), 'gateway_activity_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_gateway_activity_log_whatsapp_number'), 'gateway_activity_log', ['whatsapp_number'], unique=False)
    op.create_table('merchant_directory_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.Text(), nullable=True),
    sa.Column('phone_number_raw', sa.Text(), nullable=False),
    sa.Column('phone_number_normalized', sa.Text(), nullable=False),
    sa.Column('business_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_directory_entries_merchant_id'), 'merchant_directory_entries', ['merchant_id'], unique=True)
    op.create_index(op.f('ix_merchant_directory_entries_phone_number_normalized'), 'merchant_directory_entries', ['phone_number_normalized'], unique=True)
    op.create_table('merchant_jwt_cache',
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('jwt_token', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_jwt_cache')
    op.drop_index(op.f('ix_merchant_directory_entries_phone_number_normalized'), table_name='merchant_directory_entries')
    op.drop_index(op.f('ix_merchant_directory_entries_merchant_id'), table_name='merchant_directory_entries')
    op.drop_table('merchant_directory_entries')
    op.drop_index(op.f('ix_gateway_activity_log_whatsapp_number'), table_name='gateway_activity_log')
    op.drop_index(op.f('ix_gateway_activity_log_correlation_id'), table_name='gateway_activity_log')
    op.drop_table('gateway_activity_log')
    op.drop_index(op.f('ix_conversation_states_whatsapp_number'), table_name='conversation_states')
    op.drop_table('conversation_states')
    # ### end Alembic commands ###
