"""add payment notification watches

Revision ID: 8128b4d7a626
Revises: b09c49de54d9
Create Date: 2026-08-30 21:28:23.977087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8128b4d7a626'
down_revision: Union[str, None] = 'b09c49de54d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_notification_watches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('payment_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('merchant_whatsapp_number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'payment_id', 'status', name='uq_payment_watch_active_per_payment')
    )
    op.create_index(op.f('ix_payment_notification_watches_merchant_id'), 'payment_notification_watches', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_notification_watches_payment_id'), 'payment_notification_watches', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_notification_watches_payment_id'), table_name='payment_notification_watches')
    op.drop_index(op.f('ix_payment_notification_watches_merchant_id'), table_name='payment_notification_watches')
    op.drop_table('payment_notification_watches')
    # ### end Alembic commands ###
